# Generated by Django 4.0.5 on 2022-07-17 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_contact_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
