# Generated by Django 4.0.5 on 2022-07-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desc',
            new_name='description',
        ),
    ]
