# Generated by Django 4.0.4 on 2022-08-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(default=False),
        ),
    ]
